apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myschool-backend-data
  namespace: myschool-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
