FROM eclipse-temurin:21-jre

WORKDIR /app

RUN mkdir -p /app/data \
    && chown -R 10001:0 /app

COPY --chown=10001:0 target/myschool-0.0.1-SNAPSHOT.jar app.jar

USER 10001

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
