CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(30) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    qualification VARCHAR(160) NOT NULL
);

CREATE TABLE IF NOT EXISTS school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    section VARCHAR(20) NOT NULL,
    room_number VARCHAR(40) NOT NULL,
    academic_year VARCHAR(20) NOT NULL,
    class_incharge_id BIGINT NOT NULL,
    CONSTRAINT fk_class_teacher FOREIGN KEY (class_incharge_id) REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL,
    weekly_hours INT NOT NULL,
    CONSTRAINT fk_subject_class FOREIGN KEY (class_id) REFERENCES school_classes(id),
    CONSTRAINT fk_subject_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    admission_number VARCHAR(40) NOT NULL UNIQUE,
    roll_number INT NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(120) NOT NULL,
    guardian_name VARCHAR(120) NOT NULL,
    guardian_phone VARCHAR(30) NOT NULL,
    address VARCHAR(300) NOT NULL,
    blood_group VARCHAR(10) NOT NULL,
    CONSTRAINT fk_student_class FOREIGN KEY (class_id) REFERENCES school_classes(id),
    CONSTRAINT uq_class_roll UNIQUE (class_id, roll_number)
);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    teacher_id BIGINT,
    student_id BIGINT,
    CONSTRAINT fk_user_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id),
    CONSTRAINT fk_user_student FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE IF NOT EXISTS attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    note VARCHAR(240),
    CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uq_student_attendance UNIQUE (student_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS test_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    test_name VARCHAR(120) NOT NULL,
    test_date DATE NOT NULL,
    marks_obtained INT NOT NULL,
    max_marks INT NOT NULL,
    teacher_remarks VARCHAR(300) NOT NULL,
    CONSTRAINT fk_report_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_report_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS schedule_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room VARCHAR(40) NOT NULL,
    notes VARCHAR(160) NOT NULL,
    CONSTRAINT fk_schedule_class FOREIGN KEY (class_id) REFERENCES school_classes(id),
    CONSTRAINT fk_schedule_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(80) NOT NULL,
    description VARCHAR(300) NOT NULL,
    location_label VARCHAR(120) NOT NULL,
    available_to_students BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS campus_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    place_type VARCHAR(80) NOT NULL,
    x_position INT NOT NULL,
    y_position INT NOT NULL,
    description VARCHAR(240) NOT NULL
);
